example.property= I AM DEV

# DataSource settings: set here your own configurations for the database 
spring.datasource.url = jdbc:postgresql://localhost:5432/licenseDb
spring.datasource.username = microservice
spring.datasource.password = 123