# DataSource settings: set here your own configurations for the database 
spring.datasource.url = jdbc:postgresql://localhost:5432/licenseDb
spring.datasource.username = microservice
spring.datasource.password = {cipher}8867656d640bb50cba00b7f42db2c3ca99ad0764dd2809dae455b2c2bd52160d
